/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlsv.cntt.View;

import com.qlsv.cntt.Hepler.InforLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author NguyenCongPC
 */
public class MenuForm extends javax.swing.JFrame {

    private SVForm form;
    private SubjectsForm subjectsForm;
    private ClassForm classForm;
    private CoreForm core;
    private KhoaForm khoaForm;
    private ChangePasswordForm changeForm;
    private RegisterAccountForm accForm;

    /**
     * Creates new form Menu
     */
    public MenuForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tblPane = new javax.swing.JTabbedPane();
        txtNameLogin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnStudent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmnCore = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmnMon = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmnKhoa = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmnLop = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmnChangePass = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmnRegister = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sinh Viên CNTT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtNameLogin.setEnabled(false);

        jLabel10.setText("Quyền đăng nhập: ");

        txtRole.setEnabled(false);

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Đăng Nhập: ");

        jMenu1.setText("Hệ Thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Thoát");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Đăng xuất");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Quản Lý");

        jmnStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnStudent.setText("Quản lý sinh viên");
        jmnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnStudentActionPerformed(evt);
            }
        });
        jMenu2.add(jmnStudent);
        jMenu2.add(jSeparator1);

        jmnCore.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnCore.setText("Quản lý điểm");
        jmnCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCoreActionPerformed(evt);
            }
        });
        jMenu2.add(jmnCore);
        jMenu2.add(jSeparator3);

        jmnMon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnMon.setText("Quản lý môn học");
        jmnMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnMonActionPerformed(evt);
            }
        });
        jMenu2.add(jmnMon);
        jMenu2.add(jSeparator4);

        jmnKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnKhoa.setText("Quản lý khoa");
        jmnKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnKhoaActionPerformed(evt);
            }
        });
        jMenu2.add(jmnKhoa);
        jMenu2.add(jSeparator5);

        jmnLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnLop.setText("Quản lý lớp");
        jmnLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLopActionPerformed(evt);
            }
        });
        jMenu2.add(jmnLop);

        jMenuBar.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jmnChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnChangePass.setText("Đổi mật khẩu");
        jmnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnChangePassActionPerformed(evt);
            }
        });
        jMenu3.add(jmnChangePass);
        jMenu3.add(jSeparator6);

        jmnRegister.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnRegister.setText("Đăng ký tài khoản sinh viên");
        jmnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRegisterActionPerformed(evt);
            }
        });
        jMenu3.add(jmnRegister);

        jMenuBar.add(jMenu3);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtRole, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tblPane, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCoreActionPerformed
        if (core == null) {
            core = new CoreForm();
            tblPane.addTab("Quản lý điểm sinh viên", core);
        }
        tblPane.setSelectedComponent(core);
    }//GEN-LAST:event_jmnCoreActionPerformed

    private void jmnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnStudentActionPerformed
        if (form == null) {
            form = new SVForm();
            tblPane.addTab("Quản lý sinh viên", form);
        }
        tblPane.setSelectedComponent(form);
    }//GEN-LAST:event_jmnStudentActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(InforLogin.taiKhoan.getVaiTro().equals("Sinh Viên")){
            jmnRegister.setEnabled(false);
            jmnChangePass.setEnabled(false);
        }
        processLogin();
    }//GEN-LAST:event_formWindowOpened

    private void jmnMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnMonActionPerformed
        if(subjectsForm == null){
            subjectsForm = new SubjectsForm();
            tblPane.add("Quản lý môn học", subjectsForm);
        }
        tblPane.setSelectedComponent(subjectsForm);
    }//GEN-LAST:event_jmnMonActionPerformed

    private void jmnLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLopActionPerformed
        if(classForm == null){
            classForm = new ClassForm();
            tblPane.add("Quản lý lớp học", classForm);
        }
        tblPane.setSelectedComponent(classForm);
    }//GEN-LAST:event_jmnLopActionPerformed

    private void jmnKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnKhoaActionPerformed
        if(khoaForm == null){
            khoaForm = new KhoaForm();
            tblPane.add("Quản lý khoa", khoaForm);
        }
        tblPane.setSelectedComponent(khoaForm);
    }//GEN-LAST:event_jmnKhoaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int choose = JOptionPane.showConfirmDialog(form, "Đăng xuất ?");
        if(choose == JOptionPane.YES_OPTION){
            dispose();
            LoginForm login = new LoginForm();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnChangePassActionPerformed
         if(changeForm == null){
            changeForm = new ChangePasswordForm();
            tblPane.add("Đổi mật khẩu", changeForm);
        }
        tblPane.setSelectedComponent(changeForm);
    }//GEN-LAST:event_jmnChangePassActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int choose = JOptionPane.showConfirmDialog(form, "Đăng xuất ?");
        if(choose == JOptionPane.YES_OPTION){
            dispose();
            LoginForm login = new LoginForm();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRegisterActionPerformed
        if(accForm == null){
            accForm = new RegisterAccountForm();
            tblPane.add("Đổi mật khẩu", accForm);
        }
        tblPane.setSelectedComponent(accForm);
    }//GEN-LAST:event_jmnRegisterActionPerformed

    private void processLogin() {
        txtNameLogin.setText(InforLogin.taiKhoan.getTaiKhoan());
        txtRole.setText(InforLogin.taiKhoan.getVaiTro());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem jmnChangePass;
    private javax.swing.JMenuItem jmnCore;
    private javax.swing.JMenuItem jmnKhoa;
    private javax.swing.JMenuItem jmnLop;
    private javax.swing.JMenuItem jmnMon;
    private javax.swing.JMenuItem jmnRegister;
    private javax.swing.JMenuItem jmnStudent;
    private javax.swing.JTabbedPane tblPane;
    private javax.swing.JTextField txtNameLogin;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
